configuration: Release

branches:
  only:
    - master

install:
  - SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%
  
before_build:
  - nuget restore src\SimpleMvcSitemap.sln

build:
  project: src\SimpleMvcSitemap.sln       
  verbosity: minimal
  
test_script:
  - ps: src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:src\packages\NUnit.Runners.2.6.4\tools\nunit-console-x86.exe "-targetargs:""src\SimpleMvcSitemap.Tests\bin\Release\SimpleMvcSitemap.Tests.dll"" /noshadow /framework:net-4.5" -filter:"+[SimpleMvcSitemap]*" -output:coverage.xml
  
after_test:
  - ps: src\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID